[variables]
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_AUDIT = 'false'

[phases.install]
dependsOn = []
cmd = 'cd server && npm install --only=production && npm install -g tsx'

[start]
cmd = 'cd server && tsx src/index.ts'