[build]
builder = "nixpacks"
buildCommand = "npm ci"

[deploy]
startCommand = "cd server && npm run dev"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3